### ISSUE TITLE
Cross reference links not working

### ISSUE THREAD

**Issue by parlinderoth** [preciofishbone/Omnia-Foundation-Docs#1]
No inline cross reference links are working when using Readthedocs.

**Comment by andtii** [comment]
we are using the inter linking wrong, we should update links to use this :doc:`Omnia feature </fundamentals/omnia-feature>`  instead of this  `Omnia features </fundamentals/omnia-feature.html>`_

**Comment by andtii** [comment]
Updated source to fix inter linking
