### ISSUE TITLE
SharePoint Provisioning - Files

### ISSUE THREAD

**Issue by andtii** [preciofishbone/Omnia-Foundation-Docs#12]
We need documentation on how to provision files to SharePoint

**Comment by baseic** [comment]
How thoroughly should we document this? Start with Page Layout, Webpart, Generic file? @andtii

**Comment by andtii** [comment]
Yep sound like a good start @baseic

**Comment by baseic** [comment]
Ready for review @andtii

**Comment by andtii** [comment]
@baseic can we mention the RenameFile method aswell, if you specify RenameFile("OldFileName.aspx") then it will rename the old file name to the new name that you have in your TenantResourceFileMapping.

**Comment by baseic** [comment]
How does that differ from the SetName(string str)?
@andtii

**Comment by andtii** [comment]
@basic The setname renames the file so it is different then the resource mapping name and deploys it using that name. The renamefile is for when you want to change your resource mapping with a new name and the file has already been provisioned to sharepoint then you specify what the old sharepoint name is and it will find that file in sharepoint and rename it to the setname name ir tenantresource name.

Example first deploy we use the setname("test1.aspx")

Second version of feature and deploy we decide that we want to change our name to setname("test2.aspx") but test1.aspx does already exist so we use the renamefile("test1.aspx") to tell omnia that it will rename the test1 to test2

This is useful for example when having page layouts and dependencies to files so that you can update filenames and use the same file

**Comment by baseic** [comment]
Updated the generic file section with a couple of lines regarding this
