### ISSUE TITLE
Document ctx.LoadIfNeeded and ctx.ExecuteQueryIfNeeded

### ISSUE THREAD

**Issue by andtii** [preciofishbone/Omnia-Foundation-Docs#14]
Lot of the times you pass Ctx around between services and dont know if stuff has loaded or if a execute is needed, document theese methods from a Performance perspective. We should have a new performance section maybe

**Comment by baseic** [comment]
Sounds like a plan. I'll start on this one today

**Comment by baseic** [comment]
Ready for verification before rebuilding docs

**Comment by andtii** [comment]
@baseic the ExecuteQueryIfNeeded has an optional enum, can we document what that does to

**Comment by andtii** [comment]
@baseic Maybe we should have sub pages under performance for example, this one would be in a page called csom. Then we have a topic list in the performance page listing the different sub pages

**Comment by baseic** [comment]
I think so too, but maybe we can do that when we add more content? We do not want to hide the info to far down in a structure if it does not make it easier for the consumers I guess

**Comment by baseic** [comment]
Didn't know about the enum, will update!

**Comment by baseic** [comment]
Ready for review @andtii

**Comment by andtii** [comment]
@baseic LGTM
