### ISSUE TITLE
Documentation of UseLiveReload

### ISSUE THREAD

**Issue by fridagit** [preciofishbone/Omnia-Foundation-Docs#19]
Do you have any documentation of the live update property?

**Comment by andtii** [comment]
@fridagit We will try to get the documentation up as soon as possible. @baseic lets have a meeting so we can the docs up for this next!

**Comment by baseic** [comment]
Hi all!

We have now added documentation about Live reload here: http://omnia-foundation.readthedocs.io/en/latest/client-side-development/live-reload.html
