### ISSUE TITLE
The new Resource mapping wizard doesn't work

### ISSUE THREAD

**Issue by fridagit** [preciofishbone/Omnia-Foundation-Docs#20]
You can't click in the map-button

**Comment by andtii** [comment]
@fridagit For the map button to be enabled you have to select a folder mapping node in the right tree. If nothing displays in the right tree you have to build your project first so the folder mappings is displayed. In the next update we will display a message if no existing mappings is found. Please report issues with Foundation/Tooling in the Omnia Foundation repository - https://github.com/preciofishbone/Omnia-Foundation
