### ISSUE TITLE
Using same "namespace" in different extension projects

### ISSUE THREAD

**Issue by Hulabandula** [preciofishbone/Omnia-Foundation-Docs#23]
Hi! if one copies e.g. a pipe.ts file to another extension project that is to be deployed to the same tenant and one does not change the name of the class, then it will override existing functionality in the bundle.js. Does the omnia bundling not add unique prefix in bundling if from other extension project?

**Comment by baseic** [comment]
This is not a Documentation issue, please add it to https://github.com/preciofishbone/Omnia-Foundation/issues

**Comment by Hulabandula** [comment]
done
