### ISSUE TITLE
Document the steps to get built-in webserver to run

### ISSUE THREAD

**Issue by andtii** [preciofishbone/Omnia-Foundation-Docs#4]
1. Need to debug a web api project the first time so VS creates the localhost certificate
2. Copy and paste the "localhost" iis certificate from Personal > Certificates to Trusted Root Certification Authorities
3. VS Needs to run in "Administrator" mode
4. document hosting enable etc

**Comment by andtii** [comment]
We should document the environment.json at the same time

**Comment by baseic** [comment]
Closed as part of #19
