### ISSUE TITLE
Provisioning Pipelines docs missing

### ISSUE THREAD

**Issue by baseic** [preciofishbone/Omnia-Foundation-Docs#6]
Missing documentation for Provisioning Pipelines

**Comment by andtii** [comment]
@baseic Can you start on this next?

**Comment by baseic** [comment]
Yes, I have now documented this, verify please 👍

**Comment by baseic** [comment]
Moved to SharePoint Provisioning section

**Comment by andtii** [comment]
@baseic What do you mean with: At this time, Provisioning Pipeline only applies to the Omnia master page?

Any file provisioned to SharePoint can be modifed

**Comment by andtii** [comment]
@baseic Title should be Provisioning Pipelines with "s" on the end 😃

**Comment by baseic** [comment]
Are you sure about the "s" thing? Is there not really just one pipeline that you inject into?

Regarding just being available to Omnia master page: That is the only resource available in BuiltinResources class that you can scope too.

**Comment by andtii** [comment]
@baseic Well yes thats true, then remove the s from "Fields" and "Image Renditions" aswell. 

Yes its the only  resource guid we provide from Foundation but you can still listen on any resource by filename, guid etc so it still valid to be used without listening to just foundations stuff. You might want to listen for something that ODM deploys and they have provided constants for their resources.

**Comment by baseic** [comment]
OK, I'll remove the "s":s and remove the part of it only working for master page

**Comment by baseic** [comment]
So now we can pleeeease close this ;)

**Comment by andtii** [comment]
Goodie
